CREATE DATABASE IF NOT EXISTS lost_and_found_campus
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_unicode_ci;

USE lost_and_found_campus;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  nim VARCHAR(32) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL UNIQUE,
  nama VARCHAR(120) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS reports (
  id VARCHAR(100) PRIMARY KEY,
  nama VARCHAR(160) NOT NULL,
  lokasi VARCHAR(160) NOT NULL,
  deskripsi TEXT NOT NULL,
  jenis VARCHAR(20) NOT NULL,
  pelapor VARCHAR(120) NOT NULL,
  kontak VARCHAR(40) NOT NULL,
  tanggal DATETIME NOT NULL,
  foto LONGTEXT NULL,
  status VARCHAR(30) NOT NULL DEFAULT 'belumDiklaim',
  user_email VARCHAR(120) NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_reports_tanggal (tanggal),
  INDEX idx_reports_jenis (jenis),
  CONSTRAINT fk_reports_user
    FOREIGN KEY (user_email) REFERENCES users(email)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS chats (
  id VARCHAR(120) PRIMARY KEY,
  barang_id VARCHAR(100) NOT NULL,
  owner_email VARCHAR(120) NULL,
  is_online TINYINT(1) NOT NULL DEFAULT 0,
  last_seen DATETIME NULL,
  unread_count INT UNSIGNED NOT NULL DEFAULT 0,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX idx_chats_owner (owner_email),
  CONSTRAINT fk_chats_report
    FOREIGN KEY (barang_id) REFERENCES reports(id)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT fk_chats_user
    FOREIGN KEY (owner_email) REFERENCES users(email)
    ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS messages (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  chat_id VARCHAR(120) NOT NULL,
  pengirim VARCHAR(120) NOT NULL,
  teks TEXT NOT NULL,
  waktu DATETIME NOT NULL,
  is_me TINYINT(1) NOT NULL DEFAULT 0,
  INDEX idx_messages_chat_time (chat_id, waktu),
  CONSTRAINT fk_messages_chat
    FOREIGN KEY (chat_id) REFERENCES chats(id)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS notifications (
  id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  notification_key CHAR(64) NOT NULL UNIQUE,
  email VARCHAR(120) NOT NULL,
  title VARCHAR(160) NOT NULL,
  message TEXT NOT NULL,
  waktu DATETIME NOT NULL,
  is_read TINYINT(1) NOT NULL DEFAULT 0,
  INDEX idx_notifications_email_time (email, waktu),
  CONSTRAINT fk_notifications_user
    FOREIGN KEY (email) REFERENCES users(email)
    ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB;

